##Mysql 셋팅
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/travel_plan_db
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: always
# always : 매번, embedded : 내장 DB만, never : 모든 동작 안함.
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
      format_sql: true